### ISSUE TITLE
Raven::Event.from_exception NoMethodError without options.

### ISSUE THREAD

**Issue by schwern** [getsentry/sentry-ruby#1220]
**Describe the bug**

5f5dd4d49894516adf2cd3132f3e1ddd2d1fab3e changed `Raven::Event.from_exception` to expect `options[:configuration]` to exist, but `options` remains an optional argument. It's unclear what the options are or how `Raven::Event.from_exception` is to be called. We find it useful for testing.

This breaks existing code which worked with 3.0.0. sentry-raven is "in maintenance mode" which is all the more reason not to break existing code. We're looking to move to sentry-ruby.

**To Reproduce**

`Raven::Event.from_exception(RuntimeError.new)`

**Expected behavior**

A Raven::Event for the exception.

**Actual behavior**

```
     NoMethodError:
       undefined method `exception_class_allowed?' for nil:NilClass
```

**Environment**
 - Ruby Version: 2.6.5
 - SDK Version: 3.1.1
 - Integration Versions (if any):
  - Railis 6.0.3.4

**Raven Config**

This is not necessary but could be helpful.

```ruby
Raven.configure do |config|
  config.dsn = ENV['SENTRY_DSN']
end
```

**Comment by st0012** [comment]
sorry for causing the issue in your app. but `Raven::Event.from_exception` was designed to be an internal API and not to be used directly by clients. what makes you want to initialize events manually in your tests though?
