### ISSUE TITLE
Scope.transaction_names breaking change in 5.18.0

### ISSUE THREAD

**Issue by ryandkerr** [getsentry/sentry-ruby#2330]
### Issue Description

[This commit](https://github.com/getsentry/sentry-ruby/commit/5c50c80a3b6a85ef0d3a48ea41f9015d0925a4c1#diff-25f1d416d5078bc336d80082f636dfd54ed55408297311a4e593ffffab1430aeL12-R13) renamed `scope.transaction_names` to `scope.transaction_name`. When I update to 5.18.0 I one of my libraries breaks with the following error `NoMethodError: undefined method 'transaction_names'`. 

Maybe `transaction_names` was never intended for external use, but should 5.18.0 indicate that this is a potential breaking change?

### Reproduction Steps

call `Sentry.get_current_scope.transaction_names`

### Expected Behavior

No errors

### Actual Behavior

`NoMethodError: undefined method 'transaction_names'`

### Ruby Version

3.2.3

### SDK Version

5.18.0
