### ISSUE TITLE
Logger missing in vanilla Rails setup

### ISSUE THREAD

**Issue by chrmod** [getsentry/sentry-ruby#1365]
**Describe the bug**

Rails crashes on startup

```
% rails s
Traceback (most recent call last):
	29: from bin/rails:4:in `<main>'
	28: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	27: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	26: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	25: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	24: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	23: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/commands.rb:18:in `<main>'
	22: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/command.rb:46:in `invoke'
	21: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/command/base.rb:69:in `perform'
	20: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	19: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	18: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	17: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/commands/server/server_command.rb:138:in `perform'
	16: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/commands/server/server_command.rb:138:in `tap'
	15: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.3.5/lib/rails/commands/server/server_command.rb:141:in `block in perform'
	14: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
	13: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
	12: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
	11: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	10: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 9: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 8: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 7: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 6: from  <project path>/config/application.rb:21:in `<main>'
	 5: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-ruby-core-4.3.1/lib/sentry-ruby.rb:68:in `init'
	 4: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-ruby-core-4.3.1/lib/sentry-ruby.rb:68:in `new'
	 3: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-ruby-core-4.3.1/lib/sentry/client.rb:17:in `initialize'
	 2: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-ruby-core-4.3.1/lib/sentry/client.rb:17:in `new'
	 1: from /Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-ruby-core-4.3.1/lib/sentry/transport/http_transport.rb:15:in `initialize'
/Users/chrmod/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-ruby-core-4.3.1/lib/sentry/transport/http_transport.rb:53:in `set_conn': undefined method `debug' for nil:NilClass (NoMethodError)
```

Problem  may be caused by https://github.com/getsentry/sentry-ruby/pull/1363 

**To Reproduce**

Follow rails integration guide

**Environment**
 - Ruby Version: 2.7.2
 - SDK Version:4.3.1
 - Integration Versions :
  - Rails 6.0

**Comment by chrmod** [comment]
A quick fix is to add a logger in Sentry.init block
```
Sentry.init do |config|
  ...
  config.logger = Sentry::Logger.new(STDOUT)
 ...
end
```

**Comment by st0012** [comment]
@chrmod I can't reproduce this on my app (old nor new). can you tell me
- what's your `sentry-rails` version? `4.3.3`?
- did you change anything on your rails logger?
- what's the result of `bundle exec rails runner "puts(Rails.logger)"`

**Comment by chrmod** [comment]
Hi @st0012, thanks for quick response.

`sentry-rails` is `4.3.3`

I've done no changes to the rails logger.

```
% bundle exec rails runner "puts(Rails.logger)"
#<ActiveSupport::Logger:0x00007fbd7ec04b60>
```

Here is `config/apllication.rb`:

```rb
require_relative 'boot'

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module NewsAppBackend
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 6.0

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration can go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded after loading
    # the framework and any gems in your application.
  end
end

Sentry.init do |config|
  config.dsn = ''
  config.breadcrumbs_logger = [:active_support_logger]

  # Set tracesSampleRate to 1.0 to capture 100%
  # of transactions for performance monitoring.
  # We recommend adjusting this value in production
  config.traces_sample_rate = 0.5
  # or
  config.traces_sampler = lambda do |context|
    true
  end
end
```

**Comment by chrmod** [comment]
The issue is gone if I move senty init to its own initializer file `config/initializers/sentry.rb`. I must have misread the documentation. Sorry for the noise.

**Comment by bino98** [comment]
I have same it. but, 

> The issue is gone if I move senty init to its own initializer

that solution is good. the problem was resolved thank you to this issue.
