### PR TITLE
Add missing initialized? checks to sentry-rails

### LINKED ISSUE #1885: Using guard to run integration tests results in undefined method `set_transaction_name' for nil:NilClass
### Issue Description

When I run my rails controller tests using guard I get an error ever since upgrading from 5.3.1 to 5.4.2.

```
Minitest::UnexpectedError:         NoMethodError: undefined method `set_transaction_name' for nil:NilClass
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sentry-rails-5.4.2/lib/sentry/rails/controller_transaction.rb:6:in `block in included'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:427:in `instance_exec'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:427:in `block in make_lambda'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:199:in `block in halting'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:512:in `block in invoke_before'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:512:in `each'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:512:in `invoke_before'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:115:in `block in run_callbacks'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `block in instrument'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `instrument'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/activerecord-6.1.6.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/abstract_controller/base.rb:165:in `process'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionview-6.1.6.1/lib/action_view/rendering.rb:39:in `process'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_controller/metal.rb:190:in `dispatch'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_controller/test_case.rb:580:in `process_controller_response'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_controller/test_case.rb:499:in `process'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/template_assertions.rb:62:in `process'
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_controller/test_case.rb:398:in `get'
            /Users/jhubert/src/myapp/test/shared/concerns/controller_authentication_test.rb:55:in `block (3 levels) in <module:JSONTest>'
            /Users/jhubert/src/myapp/test/support/helpers/test_routes_helper.rb:96:in `with_test_routing'
            /Users/jhubert/src/myapp/test/shared/concerns/controller_authentication_test.rb:54:in `block (2 levels) in <module:JSONTest>'
```

The errors seems to be because `Sentry.get_current_scope` is returning `nil` and the code expects it to always return a scope.

```ruby
module Sentry
  module Rails
    module ControllerTransaction
      def self.included(base)
        base.prepend_before_action do |controller|
          Sentry.get_current_scope.set_transaction_name("#{controller.class}##{controller.action_name}"https://github.com/getsentry/sentry-ruby/commit/f94ec04112abfe414324cf064d2d8309122f79e8
        end
      end
    end
  end
end
```

I'm able to stop the error from happening by handling the `nil`:
```ruby
Sentry.get_current_scope&.set_transaction_name("#{controller.class}##{controller.action_name}")
```

But, this code hasn't changed in 2 years so I'm assuming something else was changed in 5.4.0 that is causing `Sentry.get_current_scope` to return `nil`. I've confirmed that `Sentry.init` is being called before these tests are run so my guess is that something is causing the Thread to disconnect or fail silently between test runs.

### Reproduction Steps

Haven't had a chance to test these steps on a plain rails 7 app yet:

1. Write a controller test
2. Run the controller tests with guard (I'm using v 2.18.0 and guard-minitest v 2.4.6)

### Expected Behavior

Tests run successfully

### Actual Behavior

Tests fail with the following error:

```
Minitest::UnexpectedError:         NoMethodError: undefined method `set_transaction_name' for nil:NilClass
            /Users/jhubert/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/sentry-rails-5.4.2/lib/sentry/rails/controller_transaction.rb:6:in `block in included'
```

### Ruby Version

ruby 3.0.4p208

### SDK Version

5.4.2

### Integration and Its Version

Rails 7

### Sentry Config

_No response_

### PR DESCRIPTION
**Pull request by sl0thentr0py**
The `at_exit` `Sentry.close` call might cause these `Sentry.get_current_scope`s to return nil and break some setups.

Fixes #1885

### CODE REVIEW

File: sentry-rails/lib/sentry/rails/tracing.rb [hunk 1]
```diff
@@ -67,6 +67,7 @@ def instrument(name, payload = {}, &block)
       end
 
       def self.get_current_transaction
+        return nil unless Sentry.initialized?
         Sentry.get_current_scope.get_transaction
```
Comment (st0012) [inline sentry-rails/lib/sentry/rails/tracing.rb:71]: How about

```rb
Sentry.get_current_scope.get_transaction if Sentry.initialized?
```

**Comment by st0012** [comment]
Can you add a changelog entry too? Thx

**Comment by sl0thentr0py** [comment]
I always forget the changelog :(
I'm thinking of adding a bot for this.
Relay uses https://github.com/getsentry/relay/blob/master/.github/workflows/danger.yml

**Comment by st0012** [comment]
I thought about using GH's release to automatically generate changelogs, but it doesn't fit our release flow (having changelog before releasing).
I'd be happy to try the workflow you mentioned 👍

**Comment by st0012** [comment]
@sl0thentr0py Thanks for your kind words ❤️

**Comment by cleptric** [comment]
Sorry to chime in, but the Ruby SDK changelogs are a staple at Sentry. Pls keep this 🚀

**Review by st0012 — APPROVED** [review]

File: sentry-rails/lib/sentry/rails/controller_transaction.rb [hunk 2]
```diff
@@ -3,6 +3,7 @@ module Rails
     module ControllerTransaction
       def self.included(base)
         base.prepend_before_action do |controller|
+          return unless Sentry.initialized?
```
[the remark this answers is not in the document]
Comment (st0012) [reply sentry-rails/lib/sentry/rails/controller_transaction.rb:6]: ping @sl0thentr0py

[the remark this answers is not in the document]
Comment (sl0thentr0py) [reply sentry-rails/lib/sentry/rails/controller_transaction.rb:6]: oof my bad, thx @gareth

[the remark this answers is not in the document]
Comment (sl0thentr0py) [reply sentry-rails/lib/sentry/rails/controller_transaction.rb:6]: https://github.com/getsentry/sentry-ruby/pull/1926
